"""

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""


def fib_even_sum():
    fibevensum = 0

    i = 1
    placeholder1 = 0
    placeholder2 = 0
    while i <= 4000000:
        placeholder2 = i
        i = i + placeholder1
        placeholder1 = placeholder2
        if i % 2 == 0:
            fibevensum += i

    print(fibevensum)


fib_even_sum()
